version: "3"

includes:
  golang:
    taskfile: ./golang/taskfile.yaml
    dir: ./golang
  php:
    taskfile: ./php/taskfile.yaml
    dir: ./php

tasks:
  default:
    silent: true
    cmds:
      - task --list-all
