version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  run:
    desc: "PHP 7.4サーバーを起動"
    cmds:
      - bash run.sh

  build:
    desc: "PHP 7.4 Dockerイメージをビルド"
    cmds:
      - docker-compose build

  up:
    desc: "PHP 7.4環境をDocker Composeで起動"
    cmds:
      - docker-compose up -d

  down:
    desc: "PHP 7.4環境を停止"
    cmds:
      - docker-compose down

  shell:
    desc: "PHP 7.4コンテナにシェルでアクセス"
    cmds:
      - docker-compose exec php74 bash
